<?php

namespace Database\Seeders;

use App\Models\Content;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;

class ContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $data = [
            [
                "id" => 1,
                "pack_id" => 1,
                "name" => "Get to Work",
                "description" => "",
                "image_path" => "",
                "release_date" => "2015-03-31",
                "eu_release_date" => "2015-04-02",
                "console_release_date" => "2018-03-20",
            ],
            [
                "id" => 2,
                "pack_id" => 1,
                "name" => "Get Together",
                "description" => "",
                "image_path" => "",
                "release_date" => "2015-12-08",
                "eu_release_date" => "2015-12-10",
                "console_release_date" => "2018-09-11",
            ],
            [
                "id" => 3,
                "pack_id" => 1,
                "name" => "City Living",
                "description" => "",
                "image_path" => "",
                "release_date" => "2016-11-01",
                "eu_release_date" => "2016-11-03",
                "console_release_date" => "2017-11-14",
            ],
            [
                "id" => 4,
                "pack_id" => 1,
                "name" => "Cats & Dogs",
                "description" => "",
                "image_path" => "",
                "release_date" => "2017-11-10",
                "eu_release_date" => null,
                "console_release_date" => "2018-07-31",
            ],
            [
                "id" => 5,
                "pack_id" => 1,
                "name" => "Seasons",
                "description" => "",
                "image_path" => "",
                "release_date" => "2018-06-22",
                "eu_release_date" => null,
                "console_release_date" => "2018-11-13",
            ],
            [
                "id" => 6,
                "pack_id" => 1,
                "name" => "Get Famous",
                "description" => "",
                "image_path" => "",
                "release_date" => "2018-11-16",
                "eu_release_date" => null,
                "console_release_date" => "2019-02-14",
            ],
            [
                "id" => 7,
                "pack_id" => 1,
                "name" => "Island Living",
                "description" => "",
                "image_path" => "",
                "release_date" => "2019-06-21",
                "eu_release_date" => null,
                "console_release_date" => "2019-07-16",
            ],
            [
                "id" => 8,
                "pack_id" => 1,
                "name" => "Discover University",
                "description" => "",
                "image_path" => "",
                "release_date" => "2019-11-15",
                "eu_release_date" => null,
                "console_release_date" => "2019-12-17",
            ],
            [
                "id" => 9,
                "pack_id" => 1,
                "name" => "Eco Lifestyle",
                "description" => "",
                "image_path" => "",
                "release_date" => "2020-06-05",
                "eu_release_date" => null,
                "console_release_date" => "2020-06-05",
            ],
            [
                "id" => 10,
                "pack_id" => 1,
                "name" => "Snowy Escape",
                "description" => "",
                "image_path" => "",
                "release_date" => "2020-11-13",
                "eu_release_date" => null,
                "console_release_date" => "2020-11-13",
            ],
            [
                "id" => 11,
                "pack_id" => 1,
                "name" => "Cottage Living",
                "description" => "",
                "image_path" => "",
                "release_date" => "2021-07-22",
                "eu_release_date" => null,
                "console_release_date" => "2021-07-22",
            ],
            [
                "id" => 12,
                "pack_id" => 1,
                "name" => "High School Years",
                "description" => "",
                "image_path" => "",
                "release_date" => "2022-07-28",
                "eu_release_date" => null,
                "console_release_date" => "2022-07-28",
            ],
            [
                "id" => 13,
                "pack_id" => 1,
                "name" => "Growing Together",
                "description" => "",
                "image_path" => "",
                "release_date" => "2023-03-16",
                "eu_release_date" => null,
                "console_release_date" => "2023-03-16",
            ],
            [
                "id" => 14,
                "pack_id" => 2,
                "name" => "Outdoor Retreat",
                "description" => "",
                "image_path" => "",
                "release_date" => "2015-01-13",
                "eu_release_date" => null,
                "console_release_date" => "2018-12-04",
            ],
            [
                "id" => 15,
                "pack_id" => 2,
                "name" => "Spy Day",
                "description" => "",
                "image_path" => "",
                "release_date" => "2015-07-14",
                "eu_release_date" => null,
                "console_release_date" => "2019-04-18",
            ],
            [
                "id" => 16,
                "pack_id" => 2,
                "name" => "Dine Out",
                "description" => "",
                "image_path" => "",
                "release_date" => "2016-06-07",
                "eu_release_date" => null,
                "console_release_date" => "2018-01-08",
            ],
            [
                "id" => 17,
                "pack_id" => 2,
                "name" => "Vampires",
                "description" => "",
                "image_path" => "",
                "release_date" => "2017-01-24",
                "eu_release_date" => null,
                "console_release_date" => "2017-11-14",
            ],
            [
                "id" => 18,
                "pack_id" => 2,
                "name" => "Parenthood",
                "description" => "",
                "image_path" => "",
                "release_date" => "2017-05-30",
                "eu_release_date" => null,
                "console_release_date" => "2018-06-19",
            ],
            [
                "id" => 19,
                "pack_id" => 2,
                "name" => "Jungle Adventure",
                "description" => "",
                "image_path" => "",
                "release_date" => "2018-02-27",
                "eu_release_date" => null,
                "console_release_date" => "2018-12-04",
            ],
            [
                "id" => 20,
                "pack_id" => 2,
                "name" => "StrangerVille",
                "description" => "",
                "image_path" => "",
                "release_date" => "2019-02-24",
                "eu_release_date" => null,
                "console_release_date" => "2019-05-14",
            ],
            [
                "id" => 21,
                "pack_id" => 2,
                "name" => "Realm of Magic",
                "description" => "",
                "image_path" => "",
                "release_date" => "2019-09-10",
                "eu_release_date" => null,
                "console_release_date" => "2019-10-15",
            ],
            [
                "id" => 22,
                "pack_id" => 2,
                "name" => "Star Wars: Journey to Batuu",
                "description" => "",
                "image_path" => "",
                "release_date" => "2020-09-08",
                "eu_release_date" => null,
                "console_release_date" => "2020-09-08",
            ],
            [
                "id" => 23,
                "pack_id" => 2,
                "name" => "Dream Home Decorator",
                "description" => "",
                "image_path" => "",
                "release_date" => "2021-06-01",
                "eu_release_date" => null,
                "console_release_date" => "2021-06-01",
            ],
            [
                "id" => 24,
                "pack_id" => 2,
                "name" => "My Wedding Stories",
                "description" => "",
                "image_path" => "",
                "release_date" => "2022-02-23",
                "eu_release_date" => null,
                "console_release_date" => "2022-02-23",
            ],
            [
                "id" => 25,
                "pack_id" => 2,
                "name" => "Werewolves",
                "description" => "",
                "image_path" => "",
                "release_date" => "2022-06-16",
                "eu_release_date" => null,
                "console_release_date" => "2022-06-16",
            ],
        ];

        foreach ($data as $d) {
            Content::updateOrCreate(
                [
                    "id" => $d["id"]
                ],
                Arr::except($d, ["id"])
            );
        }
    }
}
